name = "fructose-outburst/fusion"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'Saint-Luc/fusion-cardano-validator'"

[repository]
user = "Saint-Luc"
project = "fusion-cardano-validator"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2.2.0"
source = "github"

[config]
